# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/user/application_security/sast/#available-cicd-variables
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure/
# Dependency Scanning customization: https://docs.gitlab.com/user/application_security/dependency_scanning/dependency_scanning_sbom/#customizing-analyzer-behavior
# Container Scanning customization: https://docs.gitlab.com/user/application_security/container_scanning/#customizing-analyzer-behavior
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ci/variables/#cicd-variable-precedence
stages:
- build-clean
- test
- secret-detection

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection

image: docker:latest

services:
  - docker:dind

docker-clean:
  stage: build-clean
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/clean:$CI_COMMIT_SHA .
    - docker tag $CI_REGISTRY_IMAGE/clean:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/clean:latest
    - docker push $CI_REGISTRY_IMAGE/clean:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/clean:latest
  only:
    - main