[supervisord]
nodaemon=true
logfile=/robotrio/logs/supervisord.log
pidfile=/robotrio/logs/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
user=root

[program:gazebo]
command=gz sim -r scene.world
autostart=true
autorestart=true
startretries=3
stdout_logfile=/robotrio/logs/scene.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:microxrceagent]
command=MicroXRCEAgent udp4 -p 8888
autostart=true
autorestart=true
startretries=100
stdout_logfile=/robotrio/logs/drone_xrce.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:px4]
command=px4 -w /PX4-Autopilot/ -i 1
autostart=true
autorestart=true
startretries=3
stdout_logfile=/robotrio/logs/px4.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:gz_cameras_image]
command=gz gui -c /robotrio/drone/config/cam_gui.conf
autostart=true
autorestart=true
startretries=3
stdout_logfile=/robotrio/logs/gz_image_front_camera.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:ros-gz-bridge]
command=ros2 run ros_gz_bridge parameter_bridge --ros-args -p config_file:=/robotrio/drone/config/ros-gz-bridge.conf
autostart=true
autorestart=true
startretries=3
stdout_logfile=/robotrio/logs/ros-gz-bridge.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
redirect_stderr=true
stopasgroup=true
killasgroup=true
environment=FASTDDS_DEFAULT_PROFILES_FILE="/robotrio/drone/config/fastdds.conf"
